{
    "name": "Hotel_management",
    "version": "15.0.1.0.0",
    "depends": ["base", "mail"],
    "author": "bizzappdev",
    "website": "https://www.bizzappdev.com",
    "category": "Administration",
    "summary": "Hotel management tool",
    "data": [
        "security/ir.model.access.csv",
        "data/hotel_sequence_data.xml",
        "data/hotel_cron_data.xml",
        "data/hotel_system_parameters.xml",
        "data/room_reservation_confirmed_email_template.xml",
        "data/room_reservation_reminder_template.xml",
        "data/restraunt_reservation_direct_confirmed_email_template.xml",
        "data/restraunt_reservation_guests_confirmed_email_template.xml",
        "wizard/hotel_room_service_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/restraunt_reservation_views.xml",
        "views/restraunt_tables_views.xml",
        "views/hotel_reservation_views.xml",
        "views/hotel_room_type_views.xml",
        "views/hotel_room_services_views.xml",
        "views/food_product_views.xml",
        "views/hotel_main_menu_views.xml",
    ],
    "installable": True,
    "license": "LGPL-3",
    "demo": ["data/food_demo.xml"],
}
