{
    "name": "sale_order",
    "version": "15.0.1.0.0",
    "depends": [
        "base",
        "sale",
        "sale_management",
        "account",
        "delivery",
        "purchase",
        "project",
        "mrp",
    ],
    "author": "bizzappdev",
    "website": "https://www.bizzappdev.com",
    "category": "",
    "summary": "",
    "data": [
        "views/sale_order.xml",
        "views/account_move.xml",
        "views/purchase_order.xml",
        "views/stock_picking.xml",
        "views/project_views.xml",
        "views/mrp_production_views.xml",
    ],
    "installable": True,
    "license": "LGPL-3",
}
