{
    "name": "school_management",
    "version": "15.0.1.0.0",
    "depends": ["base", "mail", "base_automation"],
    "author": "bizzappdev",
    "website": "https://www.bizzappdev.com",
    "category": "Administration",
    "summary": "School management tool",
    "data": [
        "report/school_student_fees_receipt.xml",
        "report/school_student_fees_receipt_template.xml",
        "data/school_sequence_data.xml",
        "data/school_system_parameters.xml",
        "data/school_cron_data.xml",
        "data/school_automated_action.xml",
        "data/school_server_action_data.xml",
        "data/school_channels.xml",
        "security/security_access_data.xml",
        "security/ir.model.access.csv",
        "wizard/school_student_pay_fees_wizard.xml",
        "wizard/school_teacher_apply_leave_wizard.xml",
        "views/school_student_views.xml",
        "views/school_principal_views.xml",
        "views/school_student_classes_views.xml",
        "views/school_student_subjects_views.xml",
        "views/school_teacher_views.xml",
        "views/school_supervisor_views.xml",
        "views/school_student_fees_views.xml",
        "views/school_teacher_leave_views.xml",
        "views/school_main_menu.xml",
    ],
    "installable": True,
    "license": "LGPL-3",
}
